/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChooseCropRouteImport } from './routes/choose-crop'
import { Route as DescribeRouteImport } from './routes/describe'
import { Route as HomeRouteImport } from './routes/home'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as ResultRouteImport } from './routes/result'
import { Route as StepsRouteImport } from './routes/steps'
import { Route as VoiceRouteImport } from './routes/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseCropRoute = ChooseCropRouteImport.update({
  id: '/choose-crop',
  path: '/choose-crop',
  getParentRoute: () => rootRouteImport,
} as any)
const DescribeRoute = DescribeRouteImport.update({
  id: '/describe',
  path: '/describe',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const StepsRoute = StepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-crop': typeof ChooseCropRoute
  '/describe': typeof DescribeRoute
  '/home': typeof HomeRoute
  '/photo': typeof PhotoRoute
  '/result': typeof ResultRoute
  '/steps': typeof StepsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-crop': typeof ChooseCropRoute
  '/describe': typeof DescribeRoute
  '/home': typeof HomeRoute
  '/photo': typeof PhotoRoute
  '/result': typeof ResultRoute
  '/steps': typeof StepsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-crop': typeof ChooseCropRoute
  '/describe': typeof DescribeRoute
  '/home': typeof HomeRoute
  '/photo': typeof PhotoRoute
  '/result': typeof ResultRoute
  '/steps': typeof StepsRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-crop'
    | '/describe'
    | '/home'
    | '/photo'
    | '/result'
    | '/steps'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-crop'
    | '/describe'
    | '/home'
    | '/photo'
    | '/result'
    | '/steps'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/choose-crop'
    | '/describe'
    | '/home'
    | '/photo'
    | '/result'
    | '/steps'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseCropRoute: typeof ChooseCropRoute
  DescribeRoute: typeof DescribeRoute
  HomeRoute: typeof HomeRoute
  PhotoRoute: typeof PhotoRoute
  ResultRoute: typeof ResultRoute
  StepsRoute: typeof StepsRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-crop': {
      id: '/choose-crop'
      path: '/choose-crop'
      fullPath: '/choose-crop'
      preLoaderRoute: typeof ChooseCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/describe': {
      id: '/describe'
      path: '/describe'
      fullPath: '/describe'
      preLoaderRoute: typeof DescribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseCropRoute: ChooseCropRoute,
  DescribeRoute: DescribeRoute,
  HomeRoute: HomeRoute,
  PhotoRoute: PhotoRoute,
  ResultRoute: ResultRoute,
  StepsRoute: StepsRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
